import pandas as pd
import os
import subprocess
import re

# --- KONFIGURASI ---
EXCEL_FILE = 'metadata.xlsx'
METADATA_TEX = 'metadata.tex'
CONTENT_DIR = 'content'

def generate_metadata_tex():
    print(f"--- Membaca {EXCEL_FILE} ---")
    try:
        df = pd.read_excel(EXCEL_FILE)
        
        with open(METADATA_TEX, 'w', encoding='utf-8') as f:
            f.write("% ==========================================================\n")
            f.write(f"% GENERATED BY PYTHON FROM {EXCEL_FILE}\n")
            f.write("% JANGAN EDIT FILE INI MANUAL. EDIT EXCELNYA SAJA.\n")
            f.write("% ==========================================================\n\n")
            
            for index, row in df.iterrows():
                key = str(row['Key']).strip()
                val = str(row['Value']).strip()
                
                # Hindari baris kosong
                if key and key != 'nan':
                    # Escape karakter spesial LaTeX jika perlu (opsional, sederhana dulu)
                    # Membuat command LaTeX: \newcommand{\key}{value}
                    line = f"\\newcommand{{\\{key}}}{{{val}}}\n"
                    f.write(line)
        
        print(f"Sukses: {METADATA_TEX} berhasil dibuat.")
        
    except Exception as e:
        print(f"Error membaca Excel: {e}")

def clean_quarto_latex(tex_path):
    """
    Quarto/Pandoc menghasilkan file standalone dengan \documentclass.
    Kita harus menghapus header/preamble agar bisa di-\input ke main.tex.
    Kita hanya mengambil isi di antara \begin{document} dan \end{document}.
    """
    with open(tex_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Cari pola document environment
    pattern = re.compile(r'\\begin\{document\}(.*?)\\end\{document\}', re.DOTALL)
    match = pattern.search(content)

    if match:
        body = match.group(1).strip()
        # Tulis ulang file dengan hanya isinya saja
        with open(tex_path, 'w', encoding='utf-8') as f:
            f.write(body)
        print(f"  -> Cleaned: Header dihapus dari {tex_path}")
    else:
        # Jika tidak ada begin document (misal file sangat pendek/error), biarkan saja
        print(f"  -> Warning: Tidak menemukan env document di {tex_path}, membiarkan apa adanya.")

def convert_qmd_to_tex():
    print(f"\n--- Konversi QMD ke LaTeX di folder '{CONTENT_DIR}' ---")
    
    files = [f for f in os.listdir(CONTENT_DIR) if f.endswith('.qmd')]
    
    for filename in files:
        qmd_path = os.path.join(CONTENT_DIR, filename)
        tex_filename = filename.replace('.qmd', '.tex')
        tex_path = os.path.join(CONTENT_DIR, tex_filename)
        
        print(f"Processing: {filename}...")
        
        # Jalankan perintah Quarto
        # --to latex: output ke latex
        try:
            cmd = ['quarto', 'render', qmd_path, '--to', 'latex', '--no-clean']
            subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            
            # Bersihkan preamble agar bisa di-input
            clean_quarto_latex(tex_path)
            
        except subprocess.CalledProcessError:
            print(f"ERROR: Gagal render {filename}")
        except FileNotFoundError:
            print("ERROR: Perintah 'quarto' tidak ditemukan. Pastikan Quarto CLI terinstall.")

if __name__ == "__main__":
    generate_metadata_tex()
    convert_qmd_to_tex()
    print("\n--- SELESAI. Silakan compile main.tex Anda ---")